include(Math)

hex2dec(RAM_OFFSET 20000000)
set(TABLE_SIZE 368)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_ROM_PAGE=${ROM_PAGE} -DCONFIG_TABLE_SIZE=${TABLE_SIZE}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" PARENT_SCOPE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DCONFIG_ROM_PAGE=${ROM_PAGE} -DCONFIG_TABLE_SIZE=${TABLE_SIZE}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" PARENT_SCOPE)

set(LINKER_SCRIPT "${CMAKE_BINARY_DIR}/Generated/Memory.ld")
configure_file("${PROJECT_SOURCE_DIR}/Templates/MemoryTemplate.ld" "${LINKER_SCRIPT}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --specs=nosys.specs --specs=nano.specs -Xlinker --gc-sections -T ${LINKER_SCRIPT} -Xlinker -Map=${PROJECT_NAME}.map" PARENT_SCOPE)
