include(GetGitRevisionDescription)

function(extract_git_version _sw_major _sw_minor _sw_hash _sw_revision)
    git_describe(_ver_tag --abbrev=0 --tags)
    string(REPLACE "." ";" _ver_tag_splitted "${_ver_tag}")
    list(GET _ver_tag_splitted 0 _ver_sw_major)
    list(GET _ver_tag_splitted 1 _ver_sw_minor)
    git_commit_count(_ver_sw_revision)
    git_short_hash(_ver_sw_hash)
    set(${_sw_major} ${_ver_sw_major} PARENT_SCOPE)
    set(${_sw_minor} ${_ver_sw_minor} PARENT_SCOPE)
    set(${_sw_hash} ${_ver_sw_hash} PARENT_SCOPE)
    set(${_sw_revision} ${_ver_sw_revision} PARENT_SCOPE)
endfunction()

function(extract_hw_version _ver_string _hw_major _hw_minor)
    string(REPLACE "." ";" _ver_splitted "${_ver_string}")
    list(GET _ver_splitted 0 _ver_hw_major)
    list(GET _ver_splitted 1 _ver_hw_minor)
    set(${_hw_major} ${_ver_hw_major} PARENT_SCOPE)
    set(${_hw_minor} ${_ver_hw_minor} PARENT_SCOPE)
endfunction()
